server:
  port: 1234
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:daiayum.p12
#    key-store-password: daia123
#    key-alias: daiayum

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/project_ig?connectionTimeZone=Asia/Kolkata
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
